language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t prasad2099/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true prasad2099/react-test npm test

after_success:
  - docker build -t prasad2099/muilt-client ./client
  - docker build -t prasad2099/muilt-client ./nginx
  - docker build -t prasad2099/muilt-client ./server
  - docker build -t prasad2099/muilt-client ./worker


  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


  - docker push prasad2099/muilt-client
  - docker push prasad2099/muilt-nginx
  - docker push prasad2099/muilt-server
  - docker push prasad2099/muilt-worker