language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t prasad2099/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true prasad2099/react-test npm test

after_success:
  - docker build -t prasad2099/multi-client ./client
  - docker build -t prasad2099/multi-nginx ./nginx
  - docker build -t prasad2099/multi-server ./server
  - docker build -t prasad2099/multi-worker ./worker


  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


  - docker push prasad2099/multi-client
  - docker push prasad2099/multi-nginx
  - docker push prasad2099/multi-server
  - docker push prasad2099/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-south-1-478755237405
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    
